import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height: screenHeight } = Dimensions.get('window');

// ─── 颜色令牌 ──────────────────────────────────────────────────────────────
const C = {
  primary:      '#6366F1',
  primaryDark:  '#4F46E5',
  primaryLight: '#EEF2FF',
  accent:       '#10B981',
  warning:      '#F59E0B',
  danger:       '#EF4444',
  pink:         '#EC4899',
  bg:           '#F1F5F9',
  surface:      '#FFFFFF',
  surface2:     '#F8FAFF',
  text1:        '#0F172A',
  text2:        '#475569',
  text3:        '#94A3B8',
  border:       '#E2E8F0',
  high:         '#EF4444',
  med:          '#F59E0B',
  low:          '#10B981',
};

export const styles = StyleSheet.create({

  // ─── 标签筛选器 ────────────────────────────────────────────────────────
  tagFilterContainer: {
    backgroundColor: C.surface,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  tagScrollContainer: {
    paddingHorizontal: 16,
  },
  tagFilterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  selectedTagFilter: {
    opacity: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  unselectedTagFilter: {
    opacity: 0.45,
  },
  tagFilterText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    marginRight: 5,
    letterSpacing: 0.2,
  },
  unselectedTagText: {
    opacity: 0.9,
  },
  tagCountBadge: {
    backgroundColor: 'rgba(255,255,255,0.28)',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 8,
    minWidth: 18,
    alignItems: 'center',
  },
  unselectedTagCountBadge: {
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  tagCountText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  unselectedTagCountText: {
    opacity: 0.8,
  },
  selectedIndicator: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: C.surface,
    color: C.accent,
    fontSize: 9,
    fontWeight: 'bold',
    width: 15,
    height: 15,
    borderRadius: 8,
    textAlign: 'center',
    lineHeight: 15,
    borderWidth: 0,
  },

  taskList: {
    flex: 1,
    paddingTop: 10,
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: 80,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 17,
    color: C.text3,
    marginBottom: 8,
    fontWeight: '600',
  },
  emptyHint: {
    fontSize: 13,
    color: C.text3,
    textAlign: 'center',
    lineHeight: 19,
  },

  // ─── 滑动任务卡片 ──────────────────────────────────────────────────────
  swipeContainer: {
    marginHorizontal: 14,
    marginBottom: 8,
    position: 'relative',
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  // 操作按钮容器
  actionButtonsContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    width: 150,
  },
  actionButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
  },
  editButton: {
    backgroundColor: C.primary,
  },
  deleteButton: {
    backgroundColor: C.danger,
  },
  actionButtonIcon: {
    fontSize: 18,
    marginBottom: 3,
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  taskItemContainer: {
    backgroundColor: C.surface,
    borderRadius: 14,
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 13,
    paddingHorizontal: 14,
    backgroundColor: C.surface,
    borderRadius: 14,
  },
  taskLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  taskCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.bg,
  },
  taskCheckboxCompleted: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  taskContent: {
    flex: 1,
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 3,
  },
  taskName: {
    fontSize: 15,
    color: C.text1,
    fontWeight: '600',
    flex: 1,
    lineHeight: 20,
  },
  taskDescription: {
    fontSize: 12,
    color: C.text2,
    marginTop: 2,
    lineHeight: 16,
  },
  taskDueDate: {
    fontSize: 11,
    color: C.text3,
    marginTop: 4,
  },
  checkmark: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  priorityIndicator: {
    width: 4,
    height: 34,
    borderRadius: 3,
    marginLeft: 12,
  },
  taskCompleted: {
    textDecorationLine: 'line-through',
    color: C.text3,
  },
  taskOverdue: {
    color: C.danger,
  },
  textOverdue: {
    color: C.danger,
    fontWeight: '600',
  },
  taskTagBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 6,
  },
  taskTagText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },

  // ─── 搜索覆盖层 ────────────────────────────────────────────────────────
  searchOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    zIndex: 1000,
    paddingTop: Platform.OS === 'ios' ? 44 : 24,
  },
  searchContainer: {
    flex: 1,
    backgroundColor: C.surface,
    margin: 14,
    marginTop: 24,
    borderRadius: 22,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 10,
  },
  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bg,
    borderRadius: 24,
    paddingHorizontal: 14,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: C.border,
  },
  searchIcon: {
    fontSize: 15,
    marginRight: 8,
    color: C.text3,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 11,
    fontSize: 15,
    color: C.text1,
  },
  clearButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: C.text3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  cancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  cancelButtonText: {
    color: C.primary,
    fontSize: 15,
    fontWeight: '600',
  },
  pullIndicator: {
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  pullBar: {
    width: 36,
    height: 4,
    backgroundColor: C.border,
    borderRadius: 2,
    marginBottom: 4,
  },
  pullHint: {
    fontSize: 12,
    color: C.text3,
  },
  searchContent: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  historySection: {
    marginTop: 14,
  },
  historySectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: C.text1,
  },
  clearHistoryText: {
    color: C.danger,
    fontSize: 13,
    fontWeight: '500',
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: C.bg,
  },
  historyIcon: {
    fontSize: 14,
    marginRight: 12,
    color: C.text3,
  },
  historyText: {
    fontSize: 14,
    color: C.text1,
  },
  statsSection: {
    marginTop: 22,
    marginBottom: 16,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 12,
    paddingVertical: 18,
    backgroundColor: C.primaryLight,
    borderRadius: 16,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 22,
    fontWeight: '800',
    color: C.primary,
  },
  statLabel: {
    fontSize: 12,
    color: C.text2,
    marginTop: 4,
  },
  searchResultHeader: {
    fontSize: 13,
    color: C.text3,
    marginTop: 18,
    marginBottom: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    marginBottom: 8,
    backgroundColor: C.surface2,
    borderRadius: 14,
    borderLeftWidth: 3.5,
    borderLeftColor: C.primary,
  },
  taskResultLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 14,
  },
  taskResultCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.bg,
  },
  taskResultCheckboxCompleted: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  taskResultContent: {
    flex: 1,
  },
  taskResultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  taskResultName: {
    fontSize: 15,
    color: C.text1,
    fontWeight: '600',
    flex: 1,
  },
  taskResultDescription: {
    fontSize: 13,
    color: C.text2,
    marginTop: 3,
    lineHeight: 18,
  },
  taskResultDueDate: {
    fontSize: 12,
    color: C.text3,
    marginTop: 5,
  },
  taskResultRight: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  taskResultArrow: {
    fontSize: 16,
    color: C.text3,
  },
  noResultContainer: {
    alignItems: 'center',
    paddingVertical: 50,
  },
  noResultIcon: {
    fontSize: 46,
    marginBottom: 14,
    opacity: 0.4,
  },
  noResultText: {
    fontSize: 16,
    color: C.text2,
    marginBottom: 6,
    fontWeight: '600',
  },
  noResultHint: {
    fontSize: 13,
    color: C.text3,
  },

  // ─── 底部导航 ──────────────────────────────────────────────────────────
  bottomNavigation: {
    flexDirection: 'row',
    backgroundColor: C.surface,
    paddingVertical: 8,
    paddingHorizontal: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 8,
    borderTopWidth: 1,
    borderTopColor: C.border,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  bottomNavButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 7,
    borderRadius: 14,
    marginHorizontal: 4,
  },
  activeBottomNavButton: {
    backgroundColor: C.primaryLight,
  },
  bottomNavIcon: {
    fontSize: 20,
    marginBottom: 3,
    color: C.text3,
  },
  activeBottomNavIcon: {
    color: C.primary,
  },
  bottomNavText: {
    fontSize: 11,
    color: C.text3,
    fontWeight: '500',
  },
  activeBottomNavText: {
    color: C.primary,
    fontWeight: '700',
  },
});
